### ISSUE TITLE
Redirects to forum index after publishing a post

### ISSUE THREAD

**Issue by teo1978** [arduino/forum-issues#261] opened 2018-02-18 16:35 UTC
Steps to reproduce:
- reply to an existing thread or post a new thread

Expected:
should redirect you to the thread you replied to or created. That's pretty obvious, and it's what all decent forums do.

Observed:
Redirects you to the index of the subforum where the thread is located. Quite annoying.

**Comment by BallscrewBob** [comment] 2018-03-13 20:02
Also now seeing this issue.
Not getting to the topic from direct email links but the top of the forum as Per is seeing.

Category **VERY ANNOYING**

**Comment by Serjlee** [comment] 2018-03-19 12:05
I agree it's annoying, but you can actually change this behaviour in the forum settings:
https://forum.arduino.cc/index.php?action=profile;area=theme
(check `Return to topics after posting by default.`)

I think any administrator can set this as a default behavior. Maybe you can open a poll on the forum?

**Comment by BallscrewBob** [comment] 2020-08-28 06:42
This issue is now common place and seems to be a direct result of of some new software implementations about March 2020.
Was advised little can now be done about it. That seems to indicate a third party is involved.

**Comment by supernova-ws** [comment] 2020-09-14 14:17
Now by default new users start with "Return to topic after posting" enabled by default. Also it works for all users that never edited their profile.
For current users it is possible to switch off this param in their profiles and restore previous behavior or leave new default behavior.

Issue closed.

**Comment by BallscrewBob** [comment] 2020-09-15 18:11
@Serjlee
This was caused by some new software.
The setting suggested was NOT the prime cause.

**Comment by Serjlee** [comment] 2020-09-16 09:13
@BallscrewBob the issue as described by @teo1978 was just about the default configuration now tweaked by @supernova-ws 

I think it's just a case of time correlation over causation, or you are talking about a different issue altogether: either way I think we can close this now

**Closed by Serjlee** 2020-09-16 09:13 UTC
