### ISSUE TITLE
up/down within threads

### ISSUE THREAD

**Issue by dougp2** [arduino/forum-issues#257] opened 2017-12-02 02:51 UTC
Only a quibble.  When entering a thread I can use the up and down arrow keys to scroll through the thread but the Page Up/PageDown keys do not work until I left click somewhere on the page.  After that PgUp and PgDn work normally.

**Comment by per1234** [comment] 2021-04-16 01:01
Hi @dougp2. Thanks so much for reporting this bug. I am not able to reproduce any longer with the new Discourse-based forum so I'm going to close this as fixed. If you are still having the problem with the forum, feel free to comment here and I'll reopen this.

**Closed by per1234** 2021-04-16 01:01 UTC
Labels: bug
