### ISSUE TITLE
Notifications are not sent automatically. User's settings are ignored.

### ISSUE THREAD

**Issue by mastrolinux** [arduino/forum-issues#158] opened 2014-12-24 10:02 UTC
The general settings of a user are not respected. Notifications are working if the user select the button for every thread.

**Comment by nickgammon** [comment] 2015-01-09 08:07
Can you merge with https://github.com/arduino/forum-issues/issues/83 ?

That was closed, even when notifications are still not working. We need action. I am replying to threads and I have no idea when replies (to my replies) are made.

**Comment by 00alis** [comment] 2016-01-15 09:18
Still happening

**Comment by nickgammon** [comment] 2016-01-16 06:18
I haven't noticed it recently, probably for the simple reason that I reply to many threads, in multiple parts of the forum, and if I don't get notification for one of them I don't realize it. However the people in the thread may think I am ignoring them, which I regret.

In your case I think you are only involved in one or two parts of the forum, and it it more noticeable.

It is interesting that this was closed in March 2015, when in fact the bug still exists in 2016. Is this just closing the report to reduce the workload?

**Comment by mastrolinux** [comment] 2016-01-16 07:27
Hi Nick, when we introduced the new feature of having email only and not email + private messages, this bug happened again but we figured out just few weeks ago because some of us have different settings. The problem is the notification for those corner case work correctly for something like 24hours (and so pass all the tests) than either some settings is being reverted automaticall or there is a limit once triggered the notifications stop working.
@matteosuppo deeply investigated this issue but as you can see by yourself the code is not really clear:
https://github.com/SimpleMachines/SMF2.1/blob/4d2e3339cee682bce6bdce715d82e6ab2e4532aa/Sources/Subs-Post.php#L1020
https://github.com/SimpleMachines/SMF2.1/blob/d8a35b51671e9be086db27308b2fc397b0108576/Sources/Display.php#L964

If you think you can help here please let us know.

**Comment by nickgammon** [comment] 2016-01-16 20:15
I get *some* notifications. Some of these obscure issues can be hard to fix. I guessed at one stage that the notifications are done by a separate process (to avoid slowing the forum down) and that the communication between the forum and this extra process, that sits in the background emailing people, might be dodgy.

If I spot something I'll let you know.

**Comment by 00alis** [comment] 2016-04-05 13:47
@samura

**Comment by samura** [comment] 2016-04-09 14:02
I've been testing the **e-mail notifications**. If:
* you **subscribe to a topic** - you receive e-mail on the first reply (if topic still unread on a second reply, it won't send an e-mail again)
* you **subscribe to board** - you receive e-mails on new created boards (replies don't get e-mails)

**Comment by nickgammon** [comment] 2016-04-10 05:24
Notifications work some of the time. I think the problem is that whatever process is used to queue them up, sometimes loses some.

**Comment by 00alis** [comment] 2016-04-11 11:05
@samura based on what I experience on the http://forum.arduino.cc/index.php?board=101.0 board I think your are right! Thank you so much for finding a pattern there!

**Comment by 00alis** [comment] 2016-04-11 11:25
@nickgammon could you explain exactly how alerts work?
Do you get something like a PM?

**Comment by nickgammon** [comment] 2016-04-11 11:44
I don't have alerts on, so I couldn't say. I think I had them on a while ago and got some sort of popup dialog if I happened to be on the forum at the time. I don't regard these as particularly useful. They might be if you are on the forum for hours, and happen to notice them. I rely on the email notifications to let me know if a thread I posted on (maybe months ago) has new activity.

I have a suspicion that some of these go missing. I am guessing they are queued up and get dispatched "offline" (otherwise when you post a reply to a thread you have to wait while maybe hundreds of emails are sent out). So if there is a queue, perhaps it isn't always processed correctly.

It's hard to be sure, because the test is that you *didn't* get a notification for a response to a post you made months ago - but you weren't expecting one anyway.

Sometimes I get a notification for a thread, and I find that someone replied (say) two months ago, a reply I didn't get (so it looks like I ignored it) but the second reply gets through.

**Closed** 2016-06-11 10:08 UTC
Labels: bug, critical
