### ISSUE TITLE
refresh problems, sites not actual

### ISSUE THREAD

**Issue by mikrocoder** [arduino/forum-issues#314] opened 2020-11-11 16:59 UTC
Problems, problems, problems. The forum hosting is absolutely underground. I'm really fed up when the forum does not work.
My main problem is that despite login you simply don't get any current pages. You have to reload the page several times until you see the current status. This is simply not allowed. This is apparently due to cloudfare which Arduino uses. There are apparently problems with the page cache. Sometimes you want to reply and end up in a completely wrong thread and wrong subforum. Can also not be. It does not matter if I use Win10 or a Linux. It also does not matter which browser I use. These problems did not exist a year ago. 

Wouldn't it be easier to rehost the forum on a modern software base instead of fixing the thing broken?

**Comment by mikrocoder** [comment] 2020-11-11 17:06
By the way, this is the only website or forum that causes such problems. That means quite clearly. The problem is only the forum.

**Comment by BallscrewBob** [comment] 2020-11-12 13:00
There are some known issues with both cloudflare and AUTH0.

Knowing which one is caused by which element may be useful.
The random re-direct is usually AUTH0 and the common work around for that is the BACK button on the browser.
AUTH0 is a third party software so fixes for it are not always easy to implement.
AUTH0 does also suffer some login problems that affect the SSO which means having to separately log into some parts of the site.

Cloudflare issues tend to be the site being slow or not coming up at all.

**Comment by mikrocoder** [comment] 2020-11-12 18:06
I have no idea about web hosting. But I can compare. Because of this I can say that if the problems mentioned are only with the Arduino.cc forum, then it can only be because of the webhosting software used or the hoster or their hardware or all of them together. If I had to do that I would put the forum on a new and up-to-date software base.

**Comment by BallscrewBob** [comment] 2020-11-12 21:39
AFAIK the server is on its own hardware (Maybe an amazon bucket) ?
The software is SMF
Fed from CDN (cloudflare)
with AUTH0 for the authentication systems.

Identifying where your actual problem is would decide if this is a FORUM related issue in which case you are in the correct place or a more generalised WEB issue in which case you should report it to the link below and close this one or even break it down to seperate issues.
https://github.com/arduino/Arduino

A generalised complaint give nobody much to work with so fixes are almost impossible to implement.
For generalised issues see the next link below 
https://forum.arduino.cc/index.php?board=24.0

**Comment by alranel** [comment] 2021-06-07 17:27
Fixed with the migration to the new forum platform, closing

**Closed by alranel** 2021-06-07 17:27 UTC
Labels: bug
