### ISSUE TITLE
Karma disappeared from the forum

### ISSUE THREAD

**Issue by leomil72** [arduino/forum-issues#144] opened 2014-11-13 15:16 UTC
The karma points are disappeared from the forum pages (while they are still visible in the users' profiles).

**Comment by nickgammon** [comment] 2015-01-09 22:46
OK, a month has elapsed. We have two "add karma" links but no display of Karma. Is this really hard to fix? If so, why? It worked before.

![screenshot from 2015-01-10 09 44 08](https://cloud.githubusercontent.com/assets/185088/5688615/8aacb320-98ad-11e4-9ee3-4928e6319c54.png)

**Comment by nickgammon** [comment] 2015-01-10 01:37
Also see https://github.com/arduino/forum-issues/issues/156

**Comment by matteosuppo** [comment] 2015-03-09 15:37
Duplicate of #172

**Closed by matteosuppo** 2015-03-09 15:37 UTC
Labels: WorkInProgress
