### ISSUE TITLE
Forum forgets that one is logged in when clicking "updated topics"

### ISSUE THREAD

**Issue by sterretjeToo** [arduino/forum-issues#320] opened 2021-01-25 14:32 UTC
This is now becoming ridiculous. I'm logged in on the main page, click updated topics and get redirected to the main page because the system thinks that I'm not logged. Login again (need to provide credentials), need to refresh page after that so I see updated topics, click it and the story repeats.

I never had too many problems with the logins and could live with it but this is totally ridiculous.

Firefox 84.0.2, Windows 10. I did clear cookies and restarted Firefox.

Android plus Chrome still seems to be OK.

**Comment by sterretjeToo** [comment] 2021-01-26 09:02
I haven't experienced the issue for a number of hours now.

Not sure what changed.

**Comment by BallscrewBob** [comment] 2021-01-28 13:29
Maybe it is CACHE related ?

**Comment by sterretjeToo** [comment] 2021-01-28 13:42
It would be strange that it would automatically resolve itself if it was a cache issue. But I indeed did not clear the cache. Something to remember for the next time.

**Comment by BallscrewBob** [comment] 2021-02-03 03:45
Mosts OS and browsers have a set CACHE limit so occasionally they may clear on a FIFO basis.
Makes some issues a pita to chase unless you deliberately clear cache on a regular basis and on purpose as is the case here.

**Comment by sterretjeToo** [comment] 2021-02-03 04:25
Ah, thanks

**Comment by per1234** [comment] 2021-04-16 00:02
Thanks so much for the report @sterretjeToo!
Since you reported that the issue had resolved itself and there have been significant changes to the forum, I'm going to close this. Please feel free to comment here if the issue is still happening and I'll reopen.

**Closed by per1234** 2021-04-16 00:02 UTC
