### ISSUE TITLE
Incomplete list of Unread posts

### ISSUE THREAD

**Issue by ffissore** [arduino/forum-issues#52] opened 2014-10-29 11:20 UTC
<a href="https://github.com/00alis"><img src="https://avatars.githubusercontent.com/u/6151328?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [00alis](https://github.com/00alis)**
_Wednesday Oct 22, 2014 at 10:14 GMT_
_Originally opened as https://github.com/arduino/forum2/issues/52_

----

The unread posts button does not seem to be returning the unread posts, only a very small handful.
This is not like it was before where you could see all the posts you had not read and even order them so that you could pick out the ones with no replies.

for reference
https://basecamp.com/2546761/projects/6328288/messages/32602572

**Comment by matteosuppo** [comment] 2015-03-10 08:23
Hello, is this still an issue?

**Comment by nickgammon** [comment] 2015-03-10 19:29
The unread topics now appear to display correctly. However if you mark them "read" (there is a button) and then click the "-" sign next to that part of the forum you get:

>  No unread topics found since your last visit. Click here to try all unread topics. 

If you "click here" then you get:

> Database Error
> Please try again. If you come back to this error screen, report the error to an administrator.

**Comment by matteosuppo** [comment] 2015-03-12 08:01
That last thing it's a duplicate of #154

**Closed by matteosuppo** 2015-03-12 08:01 UTC
Labels: bug, critical, WorkInProgress
