### ISSUE TITLE
Bad gateway again

### ISSUE THREAD

**Issue by sterretje** [arduino/forum-issues#277] opened 2019-02-03 17:43 UTC
Title says it all; approx 19:40 South African time.

**Comment by sterretje** [comment] 2019-02-03 17:45
And it solved itself while I posted this.

**Comment by BallscrewBob** [comment] 2019-03-22 03:41
It seems to be down again 504 gateway timeouts been down since at least 5pm EST

**Comment by sterretje** [comment] 2019-06-24 08:13
Let's give this a kick so the responsible people can keep track

Error 504 Ray ID: 4ebd32c3f20fac34 • 2019-06-24 08:06:44 UTC
Gateway time-out

Win10 / Chrome 75.0.3770.80

This also happens on my mobile phone (android/chrome, no idea of versions

**Comment by per1234** [comment] 2019-06-24 08:28
It's been the same for me for about the last hour:

![Clipboard01](https://user-images.githubusercontent.com/8572152/60003335-56726180-961f-11e9-9fe9-8732abefc560.png)

**Comment by sterretje** [comment] 2019-09-15 14:53
Intermittent gateway timeout for the last hour; firefox 69.0 on windows 10.

https://auth.arduino.cc/login?client_id=forum&redirect_uri=https%3A%2F%2Fforum.arduino.cc%2F&state=1951092972&scope=profile%3Acore+profile%3Apublic+profile%3Acontact+offline&response_type=code

**Comment by sterretje** [comment] 2019-09-15 17:22
It seems to be working again.

**Comment by BallscrewBob** [comment] 2019-09-15 17:53
Same here on Chrome and even if I do get in some forum page OPTIONS are often missing.
They are working on it as we speak.

**Comment by sterretjeToo** [comment] 2020-07-20 12:09
Just to let you know that this still poses an issue

502, 504 and 524 errors and the site is terribly slow.

**Comment by BallscrewBob** [comment] 2020-07-30 02:29
Aaaand yet again....Hard to moderate with it going down so often...The warning signs were there about 4 hours before it went belly up...Same thing every time with the times new roman font starting to display (fall back font) and general sluggishness.

**Comment by sterretjeToo** [comment] 2020-07-30 02:50
> 
> 
> Aaaand yet again....Hard to moderate with it going down so often...The warning signs were there about 4 hours before it went belly up...Same thing every time with the times new roman font starting to display (fall back font) and general sluggishness.

Confirmed

**Comment by sterretjeToo** [comment] 2020-08-30 11:15
Again, 502 and 503 errors.

**Comment by sterretjeToo** [comment] 2020-08-30 13:18
And solved again, possibly about an hour ago.

**Comment by BallscrewBob** [comment] 2020-08-31 13:42
I do so wish we could fix that one !
Bain of my and most other users life's

**Comment by BallscrewBob** [comment] 2020-09-04 16:31
Should be fixed now (again)
See Also [](https://forum.arduino.cc/index.php?topic=703500.new#new)

**Comment by BallscrewBob** [comment] 2020-09-04 16:31
Should be fixed now but see also https://forum.arduino.cc/index.php?topic=703500.new#new

**Comment by sterretjeToo** [comment] 2020-09-04 20:27
It is stable again.

Thanks bsb for the links.

**Comment by per1234** [comment] 2021-04-16 00:52
I'm going to close this because I haven't been seeing these "bad gateway" occurrences lately. We'll keep our fingers crossed that they are gone for good.

Please feel free to comment here if you are still experiencing these.

**Closed by per1234** 2021-04-16 00:52 UTC
Labels: bug
