### ISSUE TITLE
The new URL inserter is broken

### ISSUE THREAD

**Issue by leomil72** [arduino/forum-issues#143] opened 2014-11-13 15:14 UTC
New "feature", new problems.

The new URL inserter adds "hpp:// before the URL and a double quote afterthe URL link.

Example.
This is the correct URL:
http://forum.arduino.cc/index.php?topic=278746.msg1960038#msg1960038

This is what I get:
http://"http://forum.arduino.cc/index.php?topic=278746.msg1960038#msg1960038"

**Comment by matteosuppo** [comment] 2015-03-09 15:44
Is this still broken? I can't reproduce it, but maybe I'm looking in the wrong place

![post reply](https://cloud.githubusercontent.com/assets/1532793/6558273/960811aa-c67b-11e4-8da4-ea734ecf15fc.png)

**Comment by nickgammon** [comment] 2015-03-09 19:57
I can't reproduce that problem right now. I think it was something to do with Rich Text editing mode. Perhaps if leomil72 can describe the steps to reproduce.

**Comment by mastrolinux** [comment] 2015-03-31 09:13
No way to reproduce it. Closing, we can open it again if we will have more info.

**Closed by mastrolinux** 2015-03-31 09:13 UTC
Labels: info-needed
