### ISSUE TITLE
CODE TAGS  Arduino Forum

### ISSUE THREAD

**Issue by TomGeorge1956** [arduino/forum-issues#127] opened 2014-11-08 03:32 UTC
Hi, I am finding the number of new forum members who do not know about the code tags a pain in the a???, along with small font.

Hows about making the code tags icon BIGGER and DARKER in color and WRITE IN IT    CODE TAG, the same for all the other icons.

Even I have trouble finding it and I know about it, sorry guys but EVERYTHING has been made smaller, instead of READABLE,\.
We don't have 100cm computer monitors.
Please, the guys that are developing the forum code, go back to basics, use a 14inch laptop with NO BELLS and whistles and make it work.
[soapbox]
As I said, make everything readable and usable.
Mobile phones originally started to get smaller and smaller, they are now bigger then ever, do you wonder why, I understand you can't read what somebody has said about you on facebok or twister on and old phone.
[/soapbox]

Tom........ :)

**Comment by matteosuppo** [comment] 2015-03-09 16:05
duplicate of #174

**Closed by matteosuppo** 2015-03-09 16:05 UTC
