### ISSUE TITLE
If I move or split a thread, I get a notification that I did it

### ISSUE THREAD

**Issue by nickgammon** [arduino/forum-issues#171] opened 2015-01-27 06:12 UTC
I have been moving and splitting threads as part of my moderator duties. Then I check my email and find a message that:

> A topic you are watching has been split into two or more topics by Nick Gammon.

Yes, I know. I know because I **am** Nick Gammon.

You don't need to notify someone, by email, of an action they only just took. They **know** they did it. This is just clutter.

**Comment by matteosuppo** [comment] 2015-03-09 10:45
Duplicate of issue #181

**Closed** 2015-03-09 15:32 UTC
