### ISSUE TITLE
Bogus error message when trying to edit a post within 5 minutes from posting

### ISSUE THREAD

**Issue by teo1978** [arduino/forum-issues#260] opened 2018-02-17 21:20 UTC
Steps to reproduce:
- post a reply to a thread
- edit it
- save

Expected: should allow you to save. 

Observed: you get a bogus error message saying: 
> You have exceeded the number of posts you can make in a 5 minutes period. Please try again later.

There's no reason to impose a wait period between _edits_ (even between new posts it's pretty questionable, but I get the concerns about spam), and even if there was, the error message is clearly wrong.

I guess this is a bug in the mechanism that is supposed to prevent you from publishing a new post within the 5-minutes period.

**Comment by per1234** [comment] 2018-02-17 23:25
Duplicate of https://github.com/arduino/forum-issues/issues/258

**Comment by KilianB** [comment] 2018-02-28 13:32
And of https://github.com/arduino/forum-issues/issues/208

**Comment by Serjlee** [comment] 2018-03-26 09:04
See https://github.com/arduino/forum-issues/issues/208#issuecomment-376096400

**Closed by Serjlee** 2018-03-26 09:04 UTC
